{ config, pkgs, lib, inputs, ... }:

{
  imports = [
    # Core hardware scanning results (generated by NixOS installation)
    ./hardware-configuration.nix
    
    # Structural module branches
    ../../modules/core/services.nix
    ../../modules/desktop/hyprland.nix
    ../../modules/themes/stylix.nix
  ];

  # Toggle capabilities defined in abstract modules
  modules.desktop.hyprland.enable = true;

  # Enable Nix experimental features system-wide so commands like
  # `nix profile add` and `github:` flake URLs work without the
  # "experimental feature 'nix-command' is disabled" error.
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Host-specific network profile
  networking.hostName = "laptop";

  # System timezone — Zurich (CET/CEST). Drives the whole system,
  # including Noctalia's clock widget (it reads local time).
  time.timeZone = "Europe/Zurich";
boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # NixOS System-Level User Account Definition (Restored)
  users.users.severin = {
    isNormalUser = true;
    description = "Severin";
    group = "severin";
    extraGroups = [ "networkmanager" "wheel" "video" "audio" ];
    shell = pkgs.zsh;
  };
  users.groups.severin = {};

  # Enable zsh (used by ghostty/yazi zsh integrations)
  programs.zsh.enable = true;
  # Low-level system debugging utilities
  environment.systemPackages = with pkgs; [
    git
    curl
    wget
    ntfs3g
    usbutils
    pciutils
    ghostty
  ];
  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    extraSpecialArgs = { inherit inputs; }; # Forwards flake inputs (like Noctalia) to user leaves
    users.severin ={
    imports = [
      ../../users/sevi/sevi.nix
      # Noctalia's home-manager module — defines programs.noctalia (the option
      # that generates + validates ~/.config/noctalia/config.toml). Without this
      # import, programs.noctalia does not exist and the bar never applies.
      inputs.noctalia.homeModules.default
    ];
    home.homeDirectory = "/home/severin";
      home.username = "severin";
  };
};
  console.keyMap = "sg";

  system.stateVersion = "23.11";
}
